/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "lymscwxgaxdafqfrdqkv"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5bXNjd3hnYXhkYWZxZnJkcWt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY0OTEwNTksImV4cCI6MjA5MjA2NzA1OX0.2L43OwkYhEW-3uw2KbDTMr39VuqP6TFLbb3ZyeVRf-U"